import { EMPLOYEE_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import {ADMIN} from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const employeeNavigationConfig: NavigationTree[] = [
    {
        key: 'employee',
        path: '',
        title: 'PEGAWAI AREA',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN],
        meta: {
            horizontalMenu: {
                layout: 'default',
            },
        },
        subMenu: [
            {
                key: 'employee.hrd',
                path: `${EMPLOYEE_PREFIX_PATH}/hrd`,
                title: 'Data Kepegawaian',
                icon: 'hrd',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.hrd.presensi',
                        path: `${EMPLOYEE_PREFIX_PATH}/hrd/presensi`,
                        title: 'Presensi Pegawai',
                        icon: 'hrd',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.hrd.pegawai',
                        path: `${EMPLOYEE_PREFIX_PATH}/hrd/pegawai`,
                        title: 'Data Pegawai',
                        icon: 'userhrd',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.hrd.manage',
                        path: `${EMPLOYEE_PREFIX_PATH}/hrd/manage`,
                        title: 'Kelola Pegawai',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'employee.finance',
                path: '',
                title: 'Data Keuangan',
                icon: 'finance',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.finance.tagihan',
                        path: `${EMPLOYEE_PREFIX_PATH}/finance/tagihansiswa`,
                        title: 'Kelola Tagihan Siswa',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.finance.nasabah',
                        path: `${EMPLOYEE_PREFIX_PATH}/finance/nasabah`,
                        title: 'Data Nasabah',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.finance.gaji',
                        path: `${EMPLOYEE_PREFIX_PATH}/finance/gaji`,
                        title: 'Kelola Gaji Pegawai',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.finance.bpjs',
                        path: `${EMPLOYEE_PREFIX_PATH}/finance/bpjs`,
                        title: 'Data BPJS Pegawai',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.finance.jurnalpendapatan',
                        path: `${EMPLOYEE_PREFIX_PATH}/finance/jurnalpendapatan`,
                        title: 'Data Jurnal Pendapatan',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    }
                ],
                
            },
            {
                key: 'employee.pengadaan',
                path: '',
                title: 'Data Pengadaan',
                icon: 'pengadaan',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.pengadaan.permintaan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/permintaan`,
                        title: 'Permintaan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.pemesanan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/pemesanan`,
                        title: 'Pemesanan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.bast',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/bast`,
                        title: 'Serah Terima Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.stok',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/stok`,
                        title: 'Data Stok Gudang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'employee.tu',
                path: '',
                title: 'Data Tata Usaha',
                icon: 'tatausaha',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.tu.tasemester',
                        path: `${EMPLOYEE_PREFIX_PATH}/tu/tasemester`,
                        title: 'Tahun Ajaran & Semester',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.tu.tingkatkelas',
                        path: `${EMPLOYEE_PREFIX_PATH}/tu/tingkatkelas`,
                        title: 'Tingkat & Kelas',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.tu.siswa',
                        path: `${EMPLOYEE_PREFIX_PATH}/tu/siswa`,
                        title: 'Kelola Siswa',
                        icon: '',
                        type: NAV_ITEM_TYPE_COLLAPSE,
                        authority: [ADMIN],
                        subMenu: 
                        [
                            {
                                key: 'employee.tu.siswamutasi',
                                path: `${EMPLOYEE_PREFIX_PATH}/tu/siswamutasi`,
                                title: 'Mutasi Siswa',
                                icon: 'accountRoleAndPermission',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN],
                                subMenu: [],
                            },
                            {
                                key: 'employee.tu.siswapindah',
                                path: `${EMPLOYEE_PREFIX_PATH}/tu/siswapindah`,
                                title: 'Siswa Pindah Kelas',
                                icon: 'accountRoleAndPermission',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN],
                                subMenu: [],
                            },
                            {
                                key: 'employee.tu.kenaikankelas',
                                path: `${EMPLOYEE_PREFIX_PATH}/tu/kenaikankelas`,
                                title: 'Kenaikan Kelas',
                                icon: 'accountRoleAndPermission',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN],
                                subMenu: [],
                            },
                            {
                                key: 'employee.tu.kelulusan',
                                path: `${EMPLOYEE_PREFIX_PATH}/tu/kelulusan`,
                                title: 'Kelulusan Siswa',
                                icon: 'accountRoleAndPermission',
                                type: NAV_ITEM_TYPE_ITEM,
                                authority: [ADMIN],
                                subMenu: [],
                            },
                        ],
                    },
                ],
            },
            {
                key: 'employee.kurikulum',
                path: '',
                title: 'Data Kurikulum',
                icon: 'kurikulum',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.pengadaan.permintaan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/permintaan`,
                        title: 'Permintaan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.pemesanan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/pemesanan`,
                        title: 'Pemesanan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.bast',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/bast`,
                        title: 'Serah Terima Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.stok',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/stok`,
                        title: 'Data Stok Gudang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'employee.cs',
                path: '',
                title: 'Data Customer Service',
                icon: 'cs',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.pengadaan.permintaan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/permintaan`,
                        title: 'Permintaan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.pemesanan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/pemesanan`,
                        title: 'Pemesanan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.bast',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/bast`,
                        title: 'Serah Terima Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.stok',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/stok`,
                        title: 'Data Stok Gudang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    }
                ],
            },
            {
                key: 'employee.guru',
                path: '',
                title: 'Data Guru',
                icon: 'guru',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN],
                subMenu: [
                    {
                        key: 'employee.pengadaan.permintaan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/permintaan`,
                        title: 'Permintaan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.pemesanan',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/pemesanan`,
                        title: 'Pemesanan Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.bast',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/bast`,
                        title: 'Serah Terima Barang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    },
                    {
                        key: 'employee.pengadaan.stok',
                        path: `${EMPLOYEE_PREFIX_PATH}/pengadaan/stok`,
                        title: 'Data Stok Gudang',
                        icon: 'accountRoleAndPermission',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN],
                        subMenu: [],
                    }
                ],
            },
        ],
    },
]

export default employeeNavigationConfig
